# ============================================================
#  Steam Unlock - bootstrap
# ============================================================
#  Short on purpose, so you can read all of it in a few seconds.
#  It does exactly three things:
#     1) asks the optional API for the current release info (hash + mirrors)
#     2) fetches install.ps1 from a list of mirrors, retrying until the SHA256 matches
#     3) runs it
#
#  It hides nothing, does not touch antivirus settings, and does not use packed
#  or memory-loaded payloads. The only remote fetches are the URLs below.
#
#  The API step is optional: if it is unreachable, the built-in hash and mirror
#  list below are used instead, and everything still works.
#
#  NOTE ON LANGUAGE: this file must stay pure ASCII. It is executed via
#  iex, and PowerShell 5.1 decodes non-ASCII bytes using the ANSI code page.
#  install.ps1 has no such limit: it is written to disk and re-read with
#  Get-Content, so it keeps its UTF-8 BOM and full Chinese output.
#
#  Maintenance: $INSTALL_SHA below is generated by sync-hashes.ps1.
#               After editing install.ps1, run that script FIRST,
#               then upload this file, then upload install.ps1.
# ============================================================

$ErrorActionPreference = 'Stop'
try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch { }

$API_BASE = 'https://api.jiangqr2026.xyz'
$RAW = 'https://raw.githubusercontent.com/jiangqr2024/steam-unlock/main/install.ps1'

# Expected SHA256 of install.ps1. Maintained only by sync-hashes.ps1.
$INSTALL_SHA = '7720BF4F9BD1C5489FA5F7768846C22AE6F6D118ED40C15B535033A391F67A3A'

$DST = Join-Path $env:TEMP 'ost-install.ps1'
$MIN = 2000

Write-Host ''
Write-Host '  Downloading installer ...' -ForegroundColor Cyan

# ---- optional release manifest -------------------------------------------
# The API, when it has been deployed, knows the authoritative hash. Using it
# removes the "stale hash in a stale bootstrap" failure mode: the client can
# learn that a newer build exists instead of insisting on an old one.
if ($env:OST_API) { $API_BASE = $env:OST_API }
$apiInfo = $null
if ($API_BASE) {
    try {
        $apiInfo = Invoke-RestMethod -Uri "$API_BASE/v1/latest" -TimeoutSec 5 -ErrorAction Stop
    } catch { $apiInfo = $null }
}
if ($apiInfo) {
    if ($apiInfo.install_sha256 -and $apiInfo.install_sha256.Length -eq 64) {
        $INSTALL_SHA = $apiInfo.install_sha256
    }
    if ($apiInfo.halt) {
        $why = 'The installer has been paused server-side.'
        if ($apiInfo.reason) { $why = [string]$apiInfo.reason }
        Write-Host ''
        Write-Host ('  Halted: ' + $why) -ForegroundColor Red
        Write-Host '  Nothing was changed on your computer.'
        Write-Host ''
        return
    }
    if ($apiInfo.note) { Write-Host ('  ' + $apiInfo.note) -ForegroundColor Yellow }
}

# ---- mirrors -------------------------------------------------------------
# Order: direct raw first (fastest when fresh), then GitHub proxies, then
# jsDelivr. raw.githubusercontent.com keeps serving the previous copy for a
# few minutes after a push, so the first mirror can legitimately return a
# stale build. The loop treats a hash mismatch as "this source is stale" and
# moves on - it does not abort.
$SRCS = @(
    $RAW,
    'https://gh-proxy.com/' + $RAW,
    'https://ghproxy.net/' + $RAW,
    'https://cdn.jsdelivr.net/gh/jiangqr2024/steam-unlock@main/install.ps1',
    'https://fastly.jsdelivr.net/gh/jiangqr2024/steam-unlock@main/install.ps1'
)

$used = $null
$h = $null
$sz = 0
$sawStale = $false
$sawTooSmall = $false
$lastErr = ''

foreach ($s in $SRCS) {
    for ($attempt = 1; $attempt -le 2; $attempt++) {
        try {
            $null = Invoke-WebRequest -Uri $s -OutFile $DST -UseBasicParsing -TimeoutSec 45
            $sz = (Get-Item $DST).Length
            if ($sz -lt $MIN) { $sawTooSmall = $true; continue }
            $h = (Get-FileHash $DST -Algorithm SHA256).Hash
            if ($h -eq $INSTALL_SHA) { $used = $s; break }
            $sawStale = $true
            break
        }
        catch {
            if ($attempt -eq 2 -and $_.Exception) { $lastErr = $_.Exception.Message }
            Start-Sleep -Milliseconds 900
        }
    }
    if ($used) { break }
}

if (-not $used) {
    Write-Host ''
    Write-Host '  Download failed. Nothing was run.' -ForegroundColor Red
    if ($sawStale) {
        Write-Host '  Reason : mirrors served a build that does not match the expected hash.'
        Write-Host '           That usually means the CDN has not refreshed yet.'
        Write-Host '  Action : wait 5-10 minutes and run the same command again.'
        Write-Host ('  expected ' + $INSTALL_SHA) -ForegroundColor DarkGray
        Write-Host ('  got      ' + $h) -ForegroundColor DarkGray
    }
    elseif ($sawTooSmall) {
        Write-Host '  Reason : mirrors answered, but the content was not the installer.'
        Write-Host '  Action : try again in a few minutes.'
    }
    else {
        Write-Host '  Reason : no mirror answered.'
        Write-Host '  Action : check your network (or enable your proxy), then run the same command again.'
        if ($lastErr) { Write-Host ('  ' + $lastErr) -ForegroundColor DarkGray }
    }
    Write-Host ('  The downloaded file is kept at ' + $DST) -ForegroundColor DarkGray
    Write-Host ''
    return
}

Write-Host '  Verified.' -ForegroundColor Green
Write-Host ''
Write-Host '  Want to see what it does first? This file is all of it:' -ForegroundColor DarkGray
Write-Host ('  notepad "' + $DST + '"') -ForegroundColor DarkGray
Write-Host ''
Write-Host '  Installing ...' -ForegroundColor Cyan
Write-Host ''

# Run via iex rather than the call operator "& $script":
# the call operator IS subject to ExecutionPolicy. Fresh Windows client installs
# default to Restricted, and even under RemoteSigned a script downloaded from the
# internet carries Mark-of-the-Web and gets blocked. iex runs a string, so it is
# unaffected. Verified: under Restricted, & fails and iex succeeds.
iex (Get-Content $DST -Raw)