# ============================================================
#  Steam Unlock - bootstrap
# ============================================================
#  Short on purpose, so you can read all of it in a few seconds.
#  It does exactly two things:
#     1) fetches install.ps1 from a list of mirrors, retrying until
#        its SHA256 matches the value pinned below
#     2) runs it
#
#  It hides nothing, does not touch antivirus settings, and does not use
#  packed or memory-loaded payloads. The only remote fetches are the
#  mirror URLs below - nothing else, and no server of our own.
#
#  NOTE ON LANGUAGE: this file must stay pure ASCII. It is executed via
#  iex, and PowerShell 5.1 decodes non-ASCII bytes using the ANSI code page.
#  install.ps1 has no such limit: it is written to disk and re-read with
#  Get-Content, so it keeps its UTF-8 BOM and full Chinese output.
#
#  NOTE ON THE API: this script deliberately does NOT contact any API.
#  There is an optional server component (see server/ in the repo) that can
#  serve short codes and release info, but the client does not depend on it:
#  no probe, no timeout, no wait. Everything runs off the static files.
#
#  Maintenance: $INSTALL_SHA below is generated by sync-hashes.ps1.
#               After editing install.ps1, run that script FIRST,
#               then upload this file, then upload install.ps1.
# ============================================================

$ErrorActionPreference = 'Stop'
try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch { }

$RAW = 'https://raw.githubusercontent.com/jiangqr2024/steam-unlock/main/install.ps1'

# Expected SHA256 of install.ps1. Maintained only by sync-hashes.ps1.
$INSTALL_SHA = '4845AA40D384E67AE75684E80B6B068DFF70601CD278E12C11A17BF3706CB547'

# Mirror order: direct raw first (fastest when it is fresh), then GitHub
# proxies, then jsDelivr. raw.githubusercontent.com keeps serving the previous
# copy for a few minutes after a push, so the first mirror can legitimately
# return a stale build. The loop below treats a hash mismatch as "this source
# is stale" and moves on - it does not abort.
# Source order, and why it is what it is:
#   1) our own Pages domain  - the ONE channel we control, and the only place that
#                              is guaranteed to hold the current install.ps1 right
#                              after a release. Measured from a mainland-China line
#                              without any proxy: reachable.
#   2) direct raw.github      - fastest when it works, but it is blocked on many
#                              mainland lines (measured: 20s timeout, zero bytes).
#   3) GitHub proxies         - usually reachable, but they cache, so right after a
#                              release they may still hand back the previous build.
#   4) jsDelivr mirrors       - reachable, but cache branch content for ~12 hours,
#                              so they lag the most after a release.
# The hash check below means a stale source is skipped rather than trusted, so
# putting our own domain first costs nothing and fixes the common failure.
$SRCS = @(
    'https://jiangqr2026.xyz/install.ps1',
    $RAW,
    'https://gh-proxy.com/' + $RAW,
    'https://ghproxy.net/' + $RAW,
    'https://cdn.jsdelivr.net/gh/jiangqr2024/steam-unlock@main/install.ps1',
    'https://fastly.jsdelivr.net/gh/jiangqr2024/steam-unlock@main/install.ps1'
)

$DST = Join-Path $env:TEMP 'ost-install.ps1'
$MIN = 2000

Write-Host ''
Write-Host '  Downloading installer ...' -ForegroundColor Cyan

$used = $null
$h = $null
$sz = 0
$sawStale = $false
$sawTooSmall = $false
$lastErr = ''

foreach ($s in $SRCS) {
    for ($attempt = 1; $attempt -le 2; $attempt++) {
        try {
            $null = Invoke-WebRequest -Uri $s -OutFile $DST -UseBasicParsing -TimeoutSec 45
            $sz = (Get-Item $DST).Length
            if ($sz -lt $MIN) { $sawTooSmall = $true; continue }
            $h = (Get-FileHash $DST -Algorithm SHA256).Hash
            if ($h -eq $INSTALL_SHA) { $used = $s; break }
            $sawStale = $true
            break
        }
        catch {
            if ($attempt -eq 2 -and $_.Exception) { $lastErr = $_.Exception.Message }
            Start-Sleep -Milliseconds 900
        }
    }
    if ($used) { break }
}

if (-not $used) {
    Write-Host ''
    Write-Host '  Download failed. Nothing was run.' -ForegroundColor Red
    if ($sawStale) {
        Write-Host '  Reason : mirrors served a build that does not match the expected hash.'
        Write-Host '           That usually means the CDN has not refreshed yet.'
        Write-Host '  Action : wait 5-10 minutes and run the same command again.'
        Write-Host ('  expected ' + $INSTALL_SHA) -ForegroundColor DarkGray
        Write-Host ('  got      ' + $h) -ForegroundColor DarkGray
    }
    elseif ($sawTooSmall) {
        Write-Host '  Reason : mirrors answered, but the content was not the installer.'
        Write-Host '  Action : try again in a few minutes.'
    }
    else {
        Write-Host '  Reason : no mirror answered.'
        Write-Host '  Action : check your network (or enable your proxy), then run the same command again.'
        if ($lastErr) { Write-Host ('  ' + $lastErr) -ForegroundColor DarkGray }
    }
    Write-Host ('  The downloaded file is kept at ' + $DST) -ForegroundColor DarkGray
    Write-Host ''
    return
}

Write-Host '  Verified.' -ForegroundColor Green
Write-Host ''
Write-Host '  Want to see what it does first? This file is all of it:' -ForegroundColor DarkGray
Write-Host ('  notepad "' + $DST + '"') -ForegroundColor DarkGray
Write-Host ''
Write-Host '  Installing ...' -ForegroundColor Cyan
Write-Host ''

# Run via iex rather than the call operator "& $script":
# the call operator IS subject to ExecutionPolicy. Fresh Windows client installs
# default to Restricted, and even under RemoteSigned a script downloaded from the
# internet carries Mark-of-the-Web and gets blocked. iex runs a string, so it is
# unaffected. Verified: under Restricted, & fails and iex succeeds.
iex (Get-Content $DST -Raw)