# ============================================================
#  Steam Unlock - bootstrap
# ============================================================
#  Short on purpose, so you can read all of it in a few seconds.
#  It does exactly three things:
#     1) fetches the real installer (install.ps1) from a list of mirrors
#     2) checks its SHA256 against the value pinned below
#     3) runs it
#
#  It hides nothing, does not touch antivirus settings, and does not use
#  packed or memory-loaded payloads. The only remote fetches are the fixed
#  URLs below.
#
#  NOTE ON LANGUAGE: this file must stay pure ASCII. It is fetched with
#  Invoke-RestMethod and handed to iex, and PowerShell 5.1 decodes that
#  without a charset hint as Latin-1 - non-ASCII bytes would come out as
#  garbage (and garbage inside a comment or string breaks the parse).
#  install.ps1 has no such limit: it is written to disk and re-read with
#  Get-Content, so it keeps its UTF-8 BOM and full Chinese output.
#
#  Maintenance: $INSTALL_SHA below is generated by sync-hashes.ps1.
#               After editing install.ps1, run that script FIRST,
#               then upload this file, then upload install.ps1.
# ============================================================

$ErrorActionPreference = 'Stop'
try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch { }

# Mirror order: direct raw first (fastest when it is fresh), then GitHub
# proxies, then jsDelivr. raw.githubusercontent.com keeps serving the
# previous copy for a few minutes after a push, so the first mirror can
# legitimately return a stale build. The loop below treats a hash mismatch
# as "this source is stale" and moves on - it does not abort.
$RAW = 'https://raw.githubusercontent.com/jiangqr2024/steam-unlock/main/install.ps1'

# Expected SHA256 of install.ps1. Maintained only by sync-hashes.ps1.
$INSTALL_SHA = '176F6BDEBCC010715324FBF4A7E97523C90B89DD173D6500CD332835E412932B'

$SRCS = @(
    $RAW,
    'https://gh-proxy.com/' + $RAW,
    'https://ghproxy.net/' + $RAW,
    'https://cdn.jsdelivr.net/gh/jiangqr2024/steam-unlock@main/install.ps1',
    'https://fastly.jsdelivr.net/gh/jiangqr2024/steam-unlock@main/install.ps1'
)

$DST = Join-Path $env:TEMP 'ost-install.ps1'
$MIN = 2000

Write-Host ''
Write-Host '  Downloading installer ...' -ForegroundColor Cyan

$used = $null
$h = $null
$sz = 0
$sawStale = $false
$sawTooSmall = $false
$lastErr = ''

foreach ($s in $SRCS) {
    for ($attempt = 1; $attempt -le 2; $attempt++) {
        try {
            $null = Invoke-WebRequest -Uri $s -OutFile $DST -UseBasicParsing -TimeoutSec 45
            $sz = (Get-Item $DST).Length
            if ($sz -lt $MIN) { $sawTooSmall = $true; continue }
            $h = (Get-FileHash $DST -Algorithm SHA256).Hash
            if ($h -eq $INSTALL_SHA) { $used = $s; break }
            $sawStale = $true
            break
        }
        catch {
            if ($attempt -eq 2 -and $_.Exception) { $lastErr = $_.Exception.Message }
            Start-Sleep -Milliseconds 900
        }
    }
    if ($used) { break }
}

if (-not $used) {
    Write-Host ''
    Write-Host '  Download failed. Nothing was run.' -ForegroundColor Red
    if ($sawStale) {
        Write-Host '  Reason : mirrors served a build that does not match the expected hash.'
        Write-Host '           That usually means the CDN has not refreshed yet.'
        Write-Host '  Action : wait 5-10 minutes and run the same command again.'
        Write-Host ('  expected ' + $INSTALL_SHA) -ForegroundColor DarkGray
        Write-Host ('  got      ' + $h) -ForegroundColor DarkGray
    }
    elseif ($sawTooSmall) {
        Write-Host '  Reason : mirrors answered, but the content was not the installer.'
        Write-Host '  Action : try again in a few minutes.'
    }
    else {
        Write-Host '  Reason : no mirror answered.'
        Write-Host '  Action : check your network (or enable your proxy), then run the same command again.'
        if ($lastErr) { Write-Host ('  ' + $lastErr) -ForegroundColor DarkGray }
    }
    Write-Host ('  The downloaded file is kept at ' + $DST) -ForegroundColor DarkGray
    Write-Host ''
    return
}

Write-Host '  Verified.' -ForegroundColor Green
Write-Host ''
Write-Host '  Want to see what it does first? This file is all of it:' -ForegroundColor DarkGray
Write-Host ('  notepad "' + $DST + '"') -ForegroundColor DarkGray
Write-Host ''
Write-Host '  Installing ...' -ForegroundColor Cyan
Write-Host ''

# Run via iex rather than the call operator "& $script":
# the call operator IS subject to ExecutionPolicy. Fresh Windows client installs
# default to Restricted, and even under RemoteSigned a script downloaded from the
# internet carries Mark-of-the-Web and gets blocked. iex runs a string, so it is
# unaffected. Verified: under Restricted, & fails and iex succeeds.
iex (Get-Content $DST -Raw)